USE [master]
GO

/****** Object:  Database [CompanyDB]    Script Date: 22.02.2020 21:16:23 ******/
CREATE DATABASE [CompanyDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CompanyDB', FILENAME = N'C:\Repositories\SQLEssential\Lesson3\CompanyDB.mdf' , SIZE = 30720KB , MAXSIZE = 102400KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'logCompanyDB', FILENAME = N'C:\Repositories\SQLEssential\Lesson3\CompanyDB.ldf' , SIZE = 5120KB , MAXSIZE = 51200KB , FILEGROWTH = 5120KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CompanyDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CompanyDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CompanyDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CompanyDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CompanyDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CompanyDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CompanyDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CompanyDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CompanyDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CompanyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CompanyDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CompanyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CompanyDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CompanyDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CompanyDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CompanyDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CompanyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CompanyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CompanyDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CompanyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CompanyDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CompanyDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CompanyDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CompanyDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CompanyDB] SET  MULTI_USER 
GO

ALTER DATABASE [CompanyDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CompanyDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CompanyDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CompanyDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CompanyDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CompanyDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CompanyDB] SET  READ_WRITE 
GO

