USE [master]
GO

/****** Object:  Database [MyFunkDB]    Script Date: 22.02.2020 21:26:59 ******/
CREATE DATABASE [MyFunkDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyFunkDB', FILENAME = N'C:\Repositories\SQLEssential\Lesson8\MyFunkDB.mdf' , SIZE = 10240KB , MAXSIZE = 102400KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'LogMyFunkDB', FILENAME = N'C:\Repositories\SQLEssential\Lesson8\MyFunkDB.ldf' , SIZE = 5120KB , MAXSIZE = 51200KB , FILEGROWTH = 5120KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyFunkDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyFunkDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyFunkDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyFunkDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyFunkDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyFunkDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyFunkDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyFunkDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyFunkDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyFunkDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyFunkDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyFunkDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyFunkDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyFunkDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyFunkDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyFunkDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MyFunkDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyFunkDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyFunkDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyFunkDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyFunkDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyFunkDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyFunkDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyFunkDB] SET RECOVERY FULL 
GO

ALTER DATABASE [MyFunkDB] SET  MULTI_USER 
GO

ALTER DATABASE [MyFunkDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyFunkDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyFunkDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyFunkDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyFunkDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyFunkDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyFunkDB] SET  READ_WRITE 
GO

