USE [master]
GO

/****** Object:  Database [HomeWork]    Script Date: 22.02.2020 21:16:05 ******/
CREATE DATABASE [HomeWork]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HomeWork', FILENAME = N'C:\Repositories\SQLEssential\Lesson2\HomeWork.mdf' , SIZE = 10240KB , MAXSIZE = 102400KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'logHomeWork', FILENAME = N'C:\Repositories\SQLEssential\Lesson2\HomeWork.ldf' , SIZE = 5120KB , MAXSIZE = 51200KB , FILEGROWTH = 5120KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HomeWork].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HomeWork] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HomeWork] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HomeWork] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HomeWork] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HomeWork] SET ARITHABORT OFF 
GO

ALTER DATABASE [HomeWork] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HomeWork] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HomeWork] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HomeWork] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HomeWork] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HomeWork] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HomeWork] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HomeWork] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HomeWork] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HomeWork] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HomeWork] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HomeWork] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HomeWork] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HomeWork] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HomeWork] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HomeWork] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HomeWork] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HomeWork] SET RECOVERY FULL 
GO

ALTER DATABASE [HomeWork] SET  MULTI_USER 
GO

ALTER DATABASE [HomeWork] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HomeWork] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HomeWork] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HomeWork] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HomeWork] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HomeWork] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HomeWork] SET  READ_WRITE 
GO

