USE [master]
GO

/****** Object:  Database [Troop]    Script Date: 22.02.2020 21:17:00 ******/
CREATE DATABASE [Troop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Troop', FILENAME = N'C:\Repositories\SQLEssential\Lesson4\Troop.mdf' , SIZE = 30720KB , MAXSIZE = 102400KB , FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'LogTroop', FILENAME = N'C:\Repositories\SQLEssential\Lesson4\Troop.ldf' , SIZE = 30720KB , MAXSIZE = 102400KB , FILEGROWTH = 5120KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Troop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Troop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Troop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Troop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Troop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Troop] SET ARITHABORT OFF 
GO

ALTER DATABASE [Troop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Troop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Troop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Troop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Troop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Troop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Troop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Troop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Troop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Troop] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Troop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Troop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Troop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Troop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Troop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Troop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Troop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Troop] SET RECOVERY FULL 
GO

ALTER DATABASE [Troop] SET  MULTI_USER 
GO

ALTER DATABASE [Troop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Troop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Troop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Troop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Troop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Troop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Troop] SET  READ_WRITE 
GO

