USE [master]
GO

/****** Object:  Database [MyJoinsDB]    Script Date: 22.02.2020 21:22:06 ******/
CREATE DATABASE [MyJoinsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyJoinsDB', FILENAME = N'C:\Repositories\SQLEssential\Lesson5\MyJoinsDB.mdf' , SIZE = 30720KB , MAXSIZE = 102400KB , FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'LogMyJoinsDB', FILENAME = N'C:\Repositories\SQLEssential\Lesson5\MyJoinsDB.ldf' , SIZE = 5120KB , MAXSIZE = 30720KB , FILEGROWTH = 5120KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyJoinsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyJoinsDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyJoinsDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyJoinsDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyJoinsDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyJoinsDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyJoinsDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyJoinsDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyJoinsDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyJoinsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyJoinsDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyJoinsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyJoinsDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyJoinsDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyJoinsDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyJoinsDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MyJoinsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyJoinsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyJoinsDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyJoinsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyJoinsDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyJoinsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyJoinsDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyJoinsDB] SET RECOVERY FULL 
GO

ALTER DATABASE [MyJoinsDB] SET  MULTI_USER 
GO

ALTER DATABASE [MyJoinsDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyJoinsDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyJoinsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyJoinsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyJoinsDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyJoinsDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyJoinsDB] SET  READ_WRITE 
GO

